default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-graphql-react_development

test:
  <<: *default
  database: rails-graphql-react_test

production:
  <<: *default
  database: rails-graphql-react_production
  username: rails-graphql-react
  password: <%= ENV['RAILS-GRAPHQL-REACT_DATABASE_PASSWORD'] %>
