development: &default
  adapter: postgresql
  encoding: unicode
  database: rails_graphql_react_dev
  username: rails_graphql_react_dev
  password: rails_graphql_react_dev
  host: localhost
  pool: 10

test:
  <<: *default
  database: rails_graphql_react_test
  username: rails_graphql_react_test
  password: rails_graphql_react_test

production:
  <<: *default
  database: <%= ENV['HEROKU_DB_NAME'] %>
  username: <%= ENV['HEROKU_DB_USERNAME'] %>
  password: <%= ENV['HEROKU_DB_PASSWORD'] %>
  host: <%= ENV['HEROKU_DB_HOSTNAME'] %>
  port: <%= ENV['HEROKU_DB_PORT'] %>
  pool: <%= ENV['HEROKU_DB_POOL'] || 5 %>
